services:
  api-gateway:
    build: .
    ports:
      - "8000:8000"
    networks:
      - ai-shared-net
    environment:
      MINIO_ENDPOINT: minio:9000
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: miniopassword
      MINIO_SECURE: False
      MINIO_BUCKET: test-bucket

networks:
  ai-shared-net:
    external: true